config/routes.rb
Rails.application.routes.draw do
  get 'dashboards/index'

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }
	resources :events

  resources :users

  root 'dashboards#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
has_many :user_events
has_many :users, through: :user_events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
				 :omniauthable, :omniauth_providers => [:facebook]

	def self.from_omniauth(auth)
		where(provider: auth.provider, uid: auth.uid.to_s).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
				user.name = auth.info.name
				user.gender = auth.extra.raw_info.gender
				user.cover = auth.extra.raw_info.cover.source
        user.email = auth.info.email
				user.image = auth.info.image
				user.real = true 
        user.password = Devise.friendly_token[0,20]
      end
	end

has_many :user_events
has_many :events, through: :user_events
end

app/models/user_event.rb
class UserEvent < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @events = Event.all
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :pin_event, :unpin_event]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show


  # this is a sequel query which will eliminate the users who have liked you, and you have also liked.
  # it will then filter out the same gender as you (should be change dto reflect your sexual preference)
  # and will only find the users who have pinned this event.
  my_matched_folk = %Q(
    SELECT * FROM users WHERE users.id NOT IN 
    (SELECT also_likes_me.user_id FROM user_events INNER JOIN user_events AS also_likes_me
      ON user_events.user_id = also_likes_me.shown_user_id
      AND also_likes_me.liked = 'yes' AND also_likes_me.event_id = #{@event.id}
      WHERE user_events.user_id = #{current_user.id} AND user_events.liked = 'yes' AND user_events.event_id = #{@event.id}) AND users.gender != "#{current_user.gender}" AND users.id IN (SELECT user_events.user_id FROM user_events 
      WHERE user_events.event_id = #{@event.id})
    )
  
  # this query will filter out any user you have liked or disliked, and is opposite gender and pinned this event.
  folk_i_liked = %Q(
    SELECT * FROM users WHERE users.id NOT IN
    (SELECT user_events.shown_user_id FROM user_events 
      WHERE user_events.user_id = #{current_user.id} AND liked != 'nil' AND user_events.event_id = #{@event.id})
      AND users.id IN (SELECT users.id FROM users WHERE users.gender != "#{current_user.gender}") AND users.id IN (SELECT user_events.user_id FROM user_events 
      WHERE user_events.event_id = #{@event.id})
    )
  
  # this will run the query to filter out likes and dislikes and pass it to the show page as @tinder
  @tinder = User.find_by_sql(folk_i_liked)

  # this will run the query to find your matches
  @matches = User.find_by_sql(my_matched_folk)

  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def pin_event
    # when a user clicks the pin event button, this will find that event, (the id is passed in the route)
    # and will add them to the users list of events/user_events table, unless that user has already pinned the event
    # it redirects back to the events page
    event = Event.find_by_id(params["id"]) 
    current_user.events << event unless current_user.events.find_by_id(event.id)
    redirect_to "/events"
  end



  def unpin_event

    # this will remove the event from the users list of events and redirect to the users page.
    event = Event.find_by_id(params["id"]) 
    current_user.events.delete(event)
    redirect_to "/users/#{current_user.id}"
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:title, :venue, :street_number, :city, :sttate, :zip, :description, :url, :image, :category)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :my_events]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def my_events
    # lists the events the user has pinned.
  end

  def tinder
    # when a user 'swipes right', this will add a new row to the user_events table with the info. and redirect to the event they came from
    UserEvent.create( user_id: current_user.id, event_id: params["event_id"].to_i, shown_user_id: params["user_id"].to_i, liked: 'yes')
    redirect_to "/events/#{params["event_id"].to_i}"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboards/index.html.erb
<html>
  <head>
    <!-- Icons & Fonts -->
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.css'>

    <style>

    * {
    transition: all 500ms ease-out;
    -webkit-transition: all 500ms ease-out;
}

html, body, section, .page {
  width: 100%;
  height: 100%;
  margin: 0;
  padding: 0;
  transition: all 1s cubic-bezier(.5, -0.005, 0.2, 1) !important;
  -webkit-transition: all 1s cubic-bezier(.5, -0.005, 0.2, 1) !important;
  color: #fff;
  background: black; /* Home background color */
  overflow-x:hidden;
  overflow-y:scroll;
}

section {
  width:400%;  
}

.page {
  position: absolute;
}


/* 
> Position and background color of individual pages
> p1 = Home
> p2 = Events
> p3 = Messages
*/

#p1 {
  left: 0;
}

#p2 {
  left: 100%;
  background: white;
}

#p3 {
  left: 200%;
  background: #ffd006;
}


ul {
 position: fixed; 
 z-index: 1;
}
#t1:target .page#p1 {
    transform: translateX(0);
}
#t2:target .page#p2 {
    transform: translateX(-90%);
}
#t3:target .page#p3 {
    transform: translateX(-190%);
}

/* Background color during page transitions */
#t2:target .page#p1, 
#t3:target .page#p1 {
  background: black;
}

/* Screen blur during page transitions */
#t2:target .page#p1 .icon, 
#t3:target .page#p1 .icon {
  -webkit-filter: blur(3px);
  filter: blur(3px);
}

.icon {
  color: #fff;
  font-size: 32px;
  display: block;
}

ul .icon:hover {
  opacity: 0.6;
}

/* Don't worry about this, will delete later */
#p1 .icon .title {
  margin-bottom: 20px;
}

/* Icons enlarge on hover */
#t2:target ul .icon,
#t3:target ul .icon {
  transform: scale(.6); 
  transition-delay: .25s;
}

/* Icons enlarge depending on what page your on */
#t2:target #dos {
  transform: scale(1.2) !important;
}

#t3:target #tres {
  transform: scale(1.2) !important;
}


ul {
  position: fixed;
  top: 0;
  bottom: 0;
  left: 0;
  /*right: 0;*/
  margin: auto;
  height: 280px;
  width: 10%;
  padding: 0;
  text-align: center;
 }

ul li {
  margin: 30px 0;
}

a {
  text-decoration: none;
  font-family: open sans, sans-serif;
}

.title, .hint {
  font-family: open sans, sans-serif;
  display: block;
}

.title {
  font-size: 38px;
}

.hint {
  font-size: 13px;
}

.hint a {
  color: #EFFF06;
  transition: all 250ms easet-out;
}

.hint a:hover {
  color: #FFF;
}

.page .icon {
  position: absolute;
  top: 0;
  bottom: 0;
  right: 10%;
  left: 0;
  width: 270px;
  height: 170px;
  margin: auto;
  text-align: center;
  font-size: 80px;
  transform: translateX(360%);
  line-height: 1.3;
}

.page#p1 .icon {
  height: 220px;
}

.page#p1 .icon {
  transform: translateX(0) !important;
}

#t2:target .page#p2 .icon {
  transform: translateX(0) !important;
  transition-delay: 1s;
}

#t3:target .page#p3 .icon {
  transform: translateX(0) !important;
  transition-delay: 1s;
}


.credit{
  position: absolute;
  bottom: 0;
  width: 100%;
  text-align: center;
  font-size: 10px;
}

.credit a {
  color: #fff
}

.homepage-event-image { 
  padding: 20px;
  }

.event-link {
  display: block;
  height: 300px;
  width: 100%;
}

.somelogo {
  padding: 0;
  margin: 0;
}

.one-event-image {
}

</style>

</head>
<body>

  <div class="ct" id="t1">
    <div class="ct" id="t2">
      <div class="ct" id="t3">
        <div class="ct" id="t4">


          <section>  
             <!-- Left navigaiton bar. Icons that use anchors to pull in page into view (#t2 = Events page) -->
             <ul>
               <a href="#t1"><li class="icon fa fa-home" id="uno"><span class="hint"> Home </span></li></a>
               <a href="#t2"><li class="icon fa fa-thumb-tack" id="dos"><span class="hint"> Events </span></li></a>
               <a href="#t3"><li class="icon fa fa-comments" id="tres"><span class="hint"> Messages </span></li></a>
             </ul>
                
                <!-- Home Page -->
                <div class="page" id="p1">
                   <li class="icon fa fa-home"><span class="title">Home<span class="hint" style="color:red;"> You haven't selected any events</span></span></li>   
                </div>
  
                <!-- Events Page -->
                <div class="page" id="p2">
                 <div class="container-fluid">
                  <h1> Events </h1>
                    <%=@events.order("date").each_slice(3) do |event_row| %>
                      <div class="row">
                        <% event_row.each do |event| %>
                          <div class="col-md-4 homepage-event-image"> 
                            <a href="events/<%=event.id%>" class="event-link" style="background: url(<%=event.image%>) center no-repeat; background-size: contain;"> </a>   
                          </div>
                        <% end %>
                      </div>
                    <%end%>
                  </div>
                </div>  
  
                <!-- Messages Page --> 
                <div class="page" id="p3">
                  <li class="icon fa fa-comments"><span class="title">Hotline Bling</span></li>
                </div> 
                
                <!-- Footer -->
                <p class="credit"> &copy; Down 2 Go <a href="https://downtogo.com/">Made in Brooklyn</a></p>
          </section>
       
        </div>
      </div>
    </div>
  </div>
</body>
</html>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :venue %><br>
    <%= f.text_field :venue %>
  </div>
  <div class="field">
    <%= f.label :street_number %><br>
    <%= f.number_field :street_number %>
	</div>
	<div class="field">
		<%= f.label :street_name %><br>
		<%= f.text_field :street_name %>
	</div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
	</div>
	<div class="field">
		<%= f.label :cost %><br>
		<%= f.text_area :cost %>
	</div>
	<div class="field">
		<%= f.label :tickets %><br>
		<%= f.text_area :tickets %>
	</div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<img class="somelogo" src="/assets/dtg-butterfl.png">
<h1> DTG </h1>

</br>


<div class="container-fluid">
  <%=@events.order("date").each_slice(3) do |event_row| %>
    <div class="row">
      <% event_row.each do |event| %>
        <div class="col-md-4 homepage-event-image"> 
            <a href="events/<%=event.id%>" class="event-link" style="background: url(<%=event.image%>) center no-repeat; background-size: contain;"> </a>   
        </div>
      <% end %>
    </div>
  <%end%>
</div>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Venue:</strong>
  <%= @event.venue %>
</p>

<p>
  <strong>Street number:</strong>
  <%= @event.street_number %>
</p>
<p>
  <strong>Street name:</strong>
  <%= @event.street_name%>
</p>

<p>
  <strong>City:</strong>
  <%= @event.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @event.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @event.zip %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @event.cost%>
</p>

<p>
  <strong>Tickets:</strong>
  <%= @event.tickets%>
</p>

<p>
  <strong>Url:</strong>
  <%= @event.url %>
</p>

<p>
  <strong>Image:</strong>
  <%= @event.image %>
</p>

<p>
  <strong>Category:</strong>
  <%= @event.category %>
</p>

<% @tinder.each do |user| %>
  <% user = User.find(user.id) %>
  <% if user.real %>
    <%= image_tag(user.image + "?type=large") %>
  <% else %>
  <%= image_tag(user.image[66..-1])%>
<% end %>
  <%= link_to "Right", "/events/#{@event.id}/users/#{user.id}/tinder" %><br>
  <%= link_to "#{user.name}", "/users/#{user.id}" %><br>
<% end %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DTG</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

<%= yield %>
<ul class="hmenu">
  <%= render 'devise/menu/registration_items' %>
  <%= render 'devise/menu/login_items' %>
</ul>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New User', new_user_path %>
<%# if user_signed_in? %>
  <li>
  <%#= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
  </li>
<%# else %>
  <li>
  <%#= link_to('Login', new_user_session_path)  %>  
  </li>
<%# end %>

app/views/users/my_events.html.erb
	<div class="container-fluid">
  <div class="row">
    <% @user.events.order("date").each do |event| %>
      <div class="col-md-6">
          <!-- iterate over each event, adding image to page that links to its page -->
          <%= link_to image_tag(event.image[8..-1], :class => "homepage-event-image"), event %>
          <%= link_to 'Remove Event', "/events/#{event.id}/unpin_event" %>
          
          <!-- <div class="homepage-event-box"> -->
            <!-- <img class="homepage-event-image" src="<%=event.image%>"> -->
          <!-- </div>   -->
      </div>
    <% end %>
  </div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div id="userimage">
	<% if @user.real %>
		<%= image_tag(@user.image + "?type=large") %>
	<% else %>
	<%= image_tag(@user.image[66..-1])%>
<% end %>
</div>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @user.gender %>
</p>

<%= link_to 'My Events', "/users/#{@user.id}/events" %>

<div class="container-fluid">
  <div class="row">
    <% @user.events.order("date").each do |event| %>
      <div class="col-md-6">
          <!-- iterate over each event, adding image to page that links to its page -->
          <%= link_to image_tag(event.image[8..-1], :class => "homepage-event-image"), event %>
          <%= link_to 'Remove Event', "/events/#{event.id}/unpin_event" %>
          
          <!-- <div class="homepage-event-box"> -->
            <!-- <img class="homepage-event-image" src="<%=event.image%>"> -->
          <!-- </div>   -->
      </div>
    <% end %>
  </div>
<%#= link_to 'Edit', edit_user_path(@user) %> |
<%#= link_to 'Back', users_path %>